[project]
name = "data-analysys-by-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "plotly>=6.1.2",
    "ruff>=0.11.12",
    "streamlit>=1.40.1",
]
