[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
base = "light"

[server]
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
enableStaticServing = false
enableWebsocketCompression = false
headless = true

[global]
developmentMode = false
unitTest = true

[logger]
level = "error"